import { FeatureGateCard } from "@/components/billing/feature-gate-card";
import { Card, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { isRoleAtLeast, requireUser } from "@/src/lib/auth";
import { getWorkspaceFeatureAccess } from "@/src/lib/billing";
import { listWorkspaceClients } from "@/src/lib/clients";
import {
  listWorkspaceRecurringInvoices,
  processDueRecurringInvoices,
} from "@/src/lib/recurring-invoices";
import { getActiveWorkspaceMembership } from "@/src/lib/workspaces";
import RecurringInvoicesClient from "./_components/RecurringInvoicesClient";

export default async function RecurringInvoicesPage() {
  const user = await requireUser();
  const membership = await getActiveWorkspaceMembership(user.id);

  if (!membership) {
    return (
      <section className="space-y-4">
        <div className="space-y-1">
          <h1 className="text-2xl font-semibold">Recurring invoices</h1>
          <p className="text-muted-foreground">No workspace assigned.</p>
        </div>
        <Card>
          <CardHeader>
            <CardTitle>Select a workspace</CardTitle>
            <CardDescription>
              Switch to a workspace to automate recurring billing.
            </CardDescription>
          </CardHeader>
        </Card>
      </section>
    );
  }

  const access = await getWorkspaceFeatureAccess(membership.workspaceId, "RECURRING_INVOICES");
  if (!access.ok) {
    return (
      <section className="space-y-6">
        <div className="space-y-1">
          <h1 className="text-2xl font-semibold">Recurring invoices</h1>
          <p className="text-muted-foreground">
            Growth unlocks invoice management and recurring billing workflows.
          </p>
        </div>
        <FeatureGateCard
          feature="RECURRING_INVOICES"
          currentPlan={access.plan}
          requiredPlan={access.requiredPlan}
        />
      </section>
    );
  }

  let autoGeneratedCount = 0;
  if (isRoleAtLeast(membership.role, "MEMBER")) {
    const generationResult = await processDueRecurringInvoices(
      membership.workspaceId,
      user.id
    );
    autoGeneratedCount = generationResult.generatedCount;
  }

  const [recurringInvoices, clients] = await Promise.all([
    listWorkspaceRecurringInvoices(membership.workspaceId),
    listWorkspaceClients(membership.workspaceId),
  ]);

  return (
    <RecurringInvoicesClient
      role={membership.role}
      workspaceName={membership.workspace.name}
      autoGeneratedCount={autoGeneratedCount}
      clients={clients.map((client) => ({
        id: client.id,
        displayName: client.displayName,
        email: client.email,
      }))}
      initialRecurringInvoices={recurringInvoices.map((entry) => ({
        ...entry,
        nextRunAt: entry.nextRunAt.toISOString(),
        createdAt: entry.createdAt.toISOString(),
        updatedAt: entry.updatedAt.toISOString(),
      }))}
    />
  );
}
